<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TenistaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tenistas')->insert([
            [
                'nombre' => 'Rafael',
                'apellido' => 'Nadal',
                'ranking' => 2,
                'pais' => 'España',
                'FechaNacimiento' => '1986-06-03',
                'edad' => 36,
                'Altura' => 1.85,
                'peso' => 85.0,
                'Mano' => 'izquierda',
                'reves' => 'dos manos',
                'entrenador' => 'Carlos Moyá',
                'totalDineroGanado' => '120000000',
                'numeroVictorias' => 950,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/n409',
                'puntos' => 6000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Roger',
                'apellido' => 'Federer',
                'ranking' => 3,
                'pais' => 'Suiza',
                'FechaNacimiento' => '1981-08-08',
                'edad' => 41,
                'Altura' => 1.85,
                'peso' => 85.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Ivan Ljubicic',
                'totalDineroGanado' => '130000000',
                'numeroVictorias' => 1250,
                'numeroDerrortas' => 250,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/f324',
                'puntos' => 5800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Novak',
                'apellido' => 'Djokovic',
                'ranking' => 1,
                'pais' => 'Serbia',
                'FechaNacimiento' => '1987-05-22',
                'edad' => 35,
                'Altura' => 1.88,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'dos manos',
                'entrenador' => 'Marian Vajda',
                'totalDineroGanado' => '140000000',
                'numeroVictorias' => 1300,
                'numeroDerrortas' => 300,
                'imagen' => 'https://atptour.com/-/media/alias/player-gladiator-headshot/d643',
                'puntos' => 6200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Andy',
                'apellido' => 'Murray',
                'ranking' => 4,
                'pais' => 'Reino Unido',
                'FechaNacimiento' => '1987-05-15',
                'edad' => 35,
                'Altura' => 1.91,
                'peso' => 84.0,
                'Mano' => 'derecha',
                'reves' => 'dos manos',
                'entrenador' => 'Jamie Delgado',
                'totalDineroGanado' => '110000000',
                'numeroVictorias' => 800,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/mc10',
                'puntos' => 5600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Stan',
                'apellido' => 'Wawrinka',
                'ranking' => 5,
                'pais' => 'Suiza',
                'FechaNacimiento' => '1985-03-28',
                'edad' => 37,
                'Altura' => 1.83,
                'peso' => 81.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Magnus Norman',
                'totalDineroGanado' => '90000000',
                'numeroVictorias' => 600,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/w367',
                'puntos' => 5400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Dominic',
                'apellido' => 'Thiem',
                'ranking' => 6,
                'pais' => 'Austria',
                'FechaNacimiento' => '1993-09-03',
                'edad' => 29,
                'Altura' => 1.85,
                'peso' => 79.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Nicolas Massu',
                'totalDineroGanado' => '80000000',
                'numeroVictorias' => 500,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/tb69',
                'puntos' => 5200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()

            ],
            [
                'nombre' => 'Alexander',
                'apellido' => 'Zverev',
                'ranking' => 7,
                'pais' => 'Alemania',
                'FechaNacimiento' => '1997-04-20',
                'edad' => 25,
                'Altura' => 1.98,
                'peso' => 90.0,
                'Mano' => 'derecha',
                'reves' => 'dos manos',
                'entrenador' => 'David Ferrer',
                'totalDineroGanado' => '70000000',
                'numeroVictorias' => 400,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/z355',
                'puntos' => 5000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Stefanos',
                'apellido' => 'Tsitsipas',
                'ranking' => 8,
                'pais' => 'Grecia',
                'FechaNacimiento' => '1998-08-12',
                'edad' => 24,
                'Altura' => 1.93,
                'peso' => 89.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Patrick Mouratoglou',
                'totalDineroGanado' => '60000000',
                'numeroVictorias' => 300,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/tb69',
                'puntos' => 4800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],

            [
                'nombre' => 'Matteo',
                'apellido' => 'Berrettini',
                'ranking' => 10,
                'pais' => 'Italia',
                'FechaNacimiento' => '1996-04-12',
                'edad' => 26,
                'Altura' => 1.96,
                'peso' => 95.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Vincenzo Santopadre',
                'totalDineroGanado' => '40000000',
                'numeroVictorias' => 100,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/bk40',
                'puntos' => 4400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],

            [
                'nombre' => 'Grigor',
                'apellido' => 'Dimitrov',
                'ranking' => 12,
                'pais' => 'Bulgaria',
                'FechaNacimiento' => '1991-05-16',
                'edad' => 31,
                'Altura' => 1.88,
                'peso' => 82.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Christian Groh',
                'totalDineroGanado' => '20000000',
                'numeroVictorias' => 30,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/d875',
                'puntos' => 4000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],

            [
                'nombre' => 'Denis',
                'apellido' => 'Shapovalov',
                'ranking' => 14,
                'pais' => 'Canadá',
                'FechaNacimiento' => '1999-04-15',
                'edad' => 23,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'izquierda',
                'reves' => 'una mano',
                'entrenador' => 'Mikhail Youzhny',
                'totalDineroGanado' => '9000000',
                'numeroVictorias' => 5,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/s741',
                'puntos' => 3600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],

            [
                'nombre' => 'Casper',
                'apellido' => 'Ruud',
                'ranking' => 16,
                'pais' => 'Noruega',
                'FechaNacimiento' => '1998-12-22',
                'edad' => 24,
                'Altura' => 1.83,
                'peso' => 78.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Christian Ruud',
                'totalDineroGanado' => '7000000',
                'numeroVictorias' => 2,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/r975',
                'puntos' => 3200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Felix',
                'apellido' => 'Auger-Aliassime',
                'ranking' => 18,
                'pais' => 'Canadá',
                'FechaNacimiento' => '2000-08-08',
                'edad' => 22,
                'Altura' => 1.93,
                'peso' => 88.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Frederic Fontang',
                'totalDineroGanado' => '6000000',
                'numeroVictorias' => 1,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/ag37',
                'puntos' => 3000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Jannik',
                'apellido' => 'Sinner',
                'ranking' => 20,
                'pais' => 'Italia',
                'FechaNacimiento' => '2001-08-16',
                'edad' => 21,
                'Altura' => 1.88,
                'peso' => 79.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Riccardo Piatti',
                'totalDineroGanado' => '5000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/s0ag',
                'puntos' => 2800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Carlos',
                'apellido' => 'Alcaraz',
                'ranking' => 22,
                'pais' => 'España',
                'FechaNacimiento' => '2003-05-05',
                'edad' => 19,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Juan Carlos Ferrero',
                'totalDineroGanado' => '4000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/a0e2',
                'puntos' => 2600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Sebastian',
                'apellido' => 'Korda',
                'ranking' => 24,
                'pais' => 'Estados Unidos',
                'FechaNacimiento' => '2000-07-05',
                'edad' => 22,
                'Altura' => 1.93,
                'peso' => 85.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Petr Korda',
                'totalDineroGanado' => '3000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/k0ah',
                'puntos' => 2400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Lorenzo',
                'apellido' => 'Musetti',
                'ranking' => 26,
                'pais' => 'Italia',
                'FechaNacimiento' => '2002-03-03',
                'edad' => 20,
                'Altura' => 1.88,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Andrea Volpini',
                'totalDineroGanado' => '2000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/m0ej',
                'puntos' => 2200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Holger Rune',
                'apellido' => 'Rune',
                'ranking' => 28,
                'pais' => 'Dinamarca',
                'FechaNacimiento' => '2003-04-29',
                'edad' => 19,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Frederik Løchte Nielsen',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/r0dg',
                'puntos' => 2000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Brandon',
                'apellido' => 'Nakashima',
                'ranking' => 30,
                'pais' => 'Estados Unidos',
                'FechaNacimiento' => '2001-08-03',
                'edad' => 21,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Pat Cash',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/n0ae',
                'puntos' => 1800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Jenson',
                'apellido' => 'Brooksby',
                'ranking' => 32,
                'pais' => 'Estados Unidos',
                'FechaNacimiento' => '2000-10-26',
                'edad' => 22,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Joseph Gilbert',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/b0cd',
                'puntos' => 1600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Emil',
                'apellido' => 'Ruusuvuori',
                'ranking' => 34,
                'pais' => 'Finlandia',
                'FechaNacimiento' => '1999-04-02',
                'edad' => 23,
                'Altura' => 1.85,
                'peso' => '80.0',
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Jarkable Nieminen',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/rh24',
                'puntos' => 1400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Alejandro',
                'apellido' => 'Davidovich Fokina',
                'ranking' => 36,
                'pais' => 'España',
                'FechaNacimiento' => '1999-06-05',
                'edad' => 23,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Javier Ferrer',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/dh50',
                'puntos' => 1200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Aslan',
                'apellido' => 'Karatsev',
                'ranking' => 38,
                'pais' => 'Rusia',
                'FechaNacimiento' => '1993-09-04',
                'edad' => 29,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Yuri Schukin',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/kc56',
                'puntos' => 1000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Mikael',
                'apellido' => 'Ymer',
                'ranking' => 40,
                'pais' => 'Suecia',
                'FechaNacimiento' => '1998-09-09',
                'edad' => 24,
                'Altura' => 1.00,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Robin Soderling',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/y268',
                'puntos' => 800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Hugo',
                'apellido' => 'Gaston',
                'ranking' => 42,
                'pais' => 'Francia',
                'FechaNacimiento' => '2000-09-26',
                'edad' => 22,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Thierry Ascione',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/g09o',
                'puntos' => 600,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Juan Manuel',
                'apellido' => 'Cerundolo',
                'ranking' => 44,
                'pais' => 'Argentina',
                'FechaNacimiento' => '2001-09-15',
                'edad' => 21,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/c0c8',
                'puntos' => 400,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'nombre' => 'Francisco',
                'apellido' => 'Cerundolo',
                'ranking' => 46,
                'pais' => 'Argentina',
                'FechaNacimiento' => '1998-11-13',
                'edad' => 24,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/c0au',
                'puntos' => 200,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Facundo',
                'apellido' => 'Bagnis',
                'ranking' => 48,
                'pais' => 'Argentina',
                'FechaNacimiento' => '1990-02-27',
                'edad' => 32,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/bf23',
                'puntos' => 100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Juan Ignacio',
                'apellido' => 'Londero',
                'ranking' => 50,
                'pais' => 'Argentina',
                'FechaNacimiento' => '1993-08-15',
                'edad' => 29,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/lb84',
                'puntos' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Federico',
                'apellido' => 'Coria',
                'ranking' => 52,
                'pais' => 'Argentina',
                'FechaNacimiento' => '1992-03-09',
                'edad' => 30,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/ce77',
                'puntos' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Thiago',
                'apellido' => 'Tirante',
                'ranking' => 54,
                'pais' => 'Argentina',
                'FechaNacimiento' => '2001-04-10',
                'edad' => 21,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/sx91',
                'puntos' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ], [
                'nombre' => 'Facundo',
                'apellido' => 'Bagnis',
                'ranking' => 58,
                'pais' => 'Argentina',
                'FechaNacimiento' => '1990-02-27',
                'edad' => 32,
                'Altura' => 1.85,
                'peso' => 80.0,
                'Mano' => 'derecha',
                'reves' => 'una mano',
                'entrenador' => 'Alejandro Cerundolo',
                'totalDineroGanado' => '1000000',
                'numeroVictorias' => 0,
                'numeroDerrortas' => 200,
                'imagen' => 'https://www.atptour.com/-/media/alias/player-gladiator-headshot/bf23',
                'puntos' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],


        ]);
    }
}
